# Generated by Django 4.2.6 on 2023-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=60)),
                ('peso_gramos', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('Snacks', 'Snacks'), ('Chocolates', 'Chocolates'), ('Proteinas', 'Proteinas'), ('Bebidas', 'Bebidas')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
