# Generated by Django 4.2.2 on 2023-10-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKeto', '0003_categoria_remove_producto_stock_alter_producto_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
