# Generated by Django 4.2.2 on 2023-10-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppKeto', '0004_alter_producto_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='Ecommerce/Ketouy/AppKeto/Static/media/productos'),
        ),
    ]
