# Generated by Django 4.2.2 on 2023-10-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppKeto', '0008_carrito_itemcarrito_delete_cliente_carrito_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
